const books = [
  { id: 1, titleEn: 'Carrie', titleDe: 'Carrie', year: 1974 },
  { id: 2, titleEn: 'The Shining', titleDe: 'Shining', year: 1977 },
  { id: 3, titleEn: '"The Stand"', titleDe: 'Das letzte Gefecht', year: 1978 },
  { id: 4, titleEn: 'The Dead Zone', titleDe: 'Das Attentat', year: 1979 },
  { id: 5, titleEn: 'Firestarter', titleDe: 'Feuerkind', year: 1980 },
  { id: 6, titleEn: 'Cujo', titleDe: 'Cujo', year: 1981 },
  { id: 7, titleEn: 'Christine', titleDe: 'Christine', year: 1983 },
  { id: 8, titleEn: 'Pet Sematary', titleDe: 'Friedhof der Kuscheltiere', year: 1983 },
  { id: 9, titleEn: 'The Talisman', titleDe: 'Der Talisman', year: 1984 },
  { id: 10, titleEn: 'It', titleDe: 'Es', year: 1986 },
  { id: 11, titleEn: 'Misery', titleDe: 'Sie', year: 1987 },
  { id: 12, titleEn: 'The Tommyknockers', titleDe: 'Das Monstrum', year: 1987 },
  { id: 13, titleEn: 'The Stand: The Complete & Uncut Edition', titleDe: 'Das letzte Gefecht (erweiterte Fassung)', year: 1990 },
  { id: 14, titleEn: 'Four Past Midnight', titleDe: 'Vier nach Mitternacht', year: 1990 },
  { id: 15, titleEn: 'The Green Mile', titleDe: 'The Green Mile', year: 1996 },
  { id: 16, titleEn: 'The Girl Who Loved Tom Gordon', titleDe: 'Das Maedchen', year: 1999 },
  { id: 17, titleEn: 'Bag of Bones', titleDe: 'Sara', year: 1998 },
  { id: 19, titleEn: 'The Running Man', titleDe: 'Menschenjagd', year: 1982 },
  { id: 20, titleEn: 'Insomnia', titleDe: 'Schlaflos', year: 1994 },
  { id: 21, titleEn: 'Rose Madder', titleDe: 'Das Bild', year: 1995 },
  { id: 22, titleEn: 'Gerald\'s Game', titleDe: 'Das Spiel', year: 1992 },
  { id: 23, titleEn: 'Needful Things', titleDe: 'In einer kleinen Stadt', year: 1991 },
  { id: 24, titleEn: 'The Waste Lands', titleDe: 'Tod', year: 1991 },
  { id: 25, titleEn: 'Wizard and Glass', titleDe: 'Glas', year: 1997 },
  { id: 26, titleEn: 'Wolves of the Calla', titleDe: 'Wolves of the Calla', year: 2003 },
  { id: 27, titleEn: 'Song of Susannah', titleDe: 'Susannah', year: 2004 },
  { id: 28, titleEn: 'The Dark Tower', titleDe: 'Der Turm', year: 2004 },
  { id: 29, titleEn: 'The Wind Through the Keyhole', titleDe: 'The Wind Through the Keyhole', year: 2012 },
  { id: 30, titleEn: 'Under the Dome', titleDe: 'Die Arena', year: 2009 },
  { id: 31, titleEn: '11/22/63', titleDe: 'Der Anschlag', year: 2011 },
  { id: 32, titleEn: 'A Happy Marriage', titleDe: 'A Happy Marriage', year: 2012 },
  { id: 33, titleEn: 'Doctor Sleep', titleDe: 'Doctor Sleep', year: 2013 },
  { id: 34, titleEn: 'The Gypsy Bride', titleDe: 'The Gypsy Bride', year: 2014 },
  { id: 35, titleEn: 'Revival', titleDe: 'Revival', year: 2014 },
  { id: 36, titleEn: 'The Outsider', titleDe: 'Der Outsider', year: 2018 },
  { id: 37, titleEn: 'If It Bleeds', titleDe: 'If It Bleeds', year: 2020 },
  { id: 38, titleEn: 'The Institute', titleDe: 'Das Institut', year: 2019 },
  { id: 39, titleEn: 'Holly', titleDe: 'Holly', year: 2023 },
  { id: 40, titleEn: 'The Life of Chuck', titleDe: 'The Life of Chuck', year: 2024 },
];

const novellas = [
  { id: 101, titleEn: 'The Body', titleDe: 'The Body', year: 1982 },
  { id: 102, titleEn: 'The Shawshank Redemption', titleDe: 'The Shawshank Redemption', year: 1982 },
  { id: 103, titleEn: 'The Apt Pupil', titleDe: 'The Apt Pupil', year: 1982 },
  { id: 104, titleEn: 'The Breathing Method', titleDe: 'The Breathing Method', year: 1982 },
];

const collections = [
  { id: 201, titleEn: 'Night Shift', titleDe: 'Nachtschicht', year: 1978 },
  { id: 202, titleEn: 'Different Seasons', titleDe: 'Fruehling, Sommer, Herbst und Tod', year: 1982 },
  { id: 203, titleEn: 'Skeleton Crew', titleDe: 'Blut', year: 1985 },
  { id: 204, titleEn: 'Everything\'s Eventual', titleDe: 'Everything\'s Eventual', year: 2002 },
];

const allWorks = [...books, ...novellas, ...collections].sort((a, b) => a.year - b.year);
